### ISSUE TITLE
TransactionBuilder throws StackOverflowException with 750 destinations

### ISSUE THREAD

**Issue by aubergemediale** [obsidianproject/ObsidianX#32]
to reproduce, create a transaction and and 750 recipient addresses. After one minute or so, there is a StackOverflowException in TransactionBuilder (line 124).

**Comment by dangershony** [comment]
Might be related

https://github.com/MetacoSA/NBitcoin/issues/751

**Comment by aubergemediale** [comment]
found a way to work around this
