### ISSUE TITLE
Double check CoinType

### ISSUE THREAD

**Issue by netsfx** [obsidianproject/ObsidianX#38]
this page https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
refers to that page for a complete list:
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

Our type is currently 442

We should decide a number and make a PR asap

**Comment by aubergemediale** [comment]
yes, we can't use 442, it's taken

**Comment by dangershony** [comment]
What if we just reuse the legacy Obsidian CoinType?

**Comment by dangershony** [comment]
PR is open for coin type 458
https://github.com/satoshilabs/slips/pull/835

**Comment by dangershony** [comment]
This has now been committed to bip44 repo, but I will keep this open til we modify the master
