### ISSUE TITLE
Feature request: Expose Header.Height

### ISSUE THREAD

**Issue by aubergemediale** [obsidianproject/ObsidianX#59]
![image](https://user-images.githubusercontent.com/12559471/70303336-a7f25f80-17ff-11ea-9e96-df03254bc3fa.png)

It would be very nice if the fullnode could expose the exact same value that the nodestats print in the above screenshot, so that it can be made accessible via the client API. Along with an educated interesting text (in the XML code comments), of the relevance of this value.

**Comment by dangershony** [comment]
Ok yes this should not be that hard.
Basically in the type `IChainState` we should add a property `BestChainTip`  or replace the one called `IsAtBestChainTip` the code to make this change is in the same place where we set `IsAtBestChainTip`

**Comment by dangershony** [comment]
This is done and will be in the code base on the next merge from blockcore

**Comment by aubergemediale** [comment]
excellent!
