### ISSUE TITLE
Create pull request to reserve final ODX CoinType

### ISSUE THREAD

**Issue by aubergemediale** [obsidianproject/ObsidianX#64]
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by dangershony** [comment]
This is already done see last comment here
https://github.com/obsidianproject/ObsidianX/issues/38

**Comment by aubergemediale** [comment]
![image](https://user-images.githubusercontent.com/12559471/70839887-5e150500-1e0f-11ea-8a23-0b04c031d0a7.png)


awesome!!! :-)
