### ISSUE TITLE
ODX - Genesis block

### ISSUE THREAD

**Issue by aubergemediale** [obsidianproject/ObsidianX#7]
- Are we choosing the right difficulty target?
- Check all places where difficulty targets are used.
- Do we need a link to an external website in the Genesis block, to prove we did not mine it earlier?
- Slightly related: Is it important top create a bitcointalk ANN to comply with conventions that are considered to be important

**Comment by dangershony** [comment]
Can we close this now? I suppose when the real network goes live we just reuse the current genesis with an updated date.

`Do we need a link to an external website in the Genesis block,` use a BTC hash?
`Slightly related: Is it important top create a bitcointalk ANN to comply with conventions that are considered to be important` yes  but unrelated to this issue I agree
